before_script:
  - npm install;
  - npm i -g firebase-tools
script:
  - gulp test 
  - gulp
after_success:
  - firebase deploy --token 1/c8IMdN8Pka7ngqs-Bu7Uw_INIHpFqR0p3dmpC6XrDCg
language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
